package com.saraasansor.api.mail.enums;

public enum EmailTemplateKey {
    MAINTENANCE_REMINDER,
    MAINTENANCE_OVERDUE,
    MAINTENANCE_COMPLETED,
    PAYMENT_REMINDER,
    PAYMENT_OVERDUE,
    PAYMENT_RECEIVED,
    INVOICE_CREATED,
    INVOICE_REMINDER,
    OFFER_CREATED,
    OFFER_APPROVED,
    OFFER_REJECTED,
    WELCOME,
    PASSWORD_RESET,
    GENERIC_NOTIFICATION,
    TEST_EMAIL,
    MARKETING_CONTACT_MESSAGE,
    MARKETING_DEMO_REQUEST,
    MARKETING_PLAN_REQUEST,
    MARKETING_TRIAL_READY,
    MARKETING_TRIAL_REMINDER
}
