-- Turkey location seed for normalized facility address model.
-- Scope:
-- 1) Seeds all 81 cities.
-- 2) Seeds district lists for major cities.
-- 3) Ensures every city has at least one district (Merkez).
-- 4) Seeds default neighborhood/region for every district.

INSERT INTO cities (name)
VALUES
    ('Adana'),
    ('Adiyaman'),
    ('Afyonkarahisar'),
    ('Agri'),
    ('Aksaray'),
    ('Amasya'),
    ('Ankara'),
    ('Antalya'),
    ('Ardahan'),
    ('Artvin'),
    ('Aydin'),
    ('Balikesir'),
    ('Bartin'),
    ('Batman'),
    ('Bayburt'),
    ('Bilecik'),
    ('Bingol'),
    ('Bitlis'),
    ('Bolu'),
    ('Burdur'),
    ('Bursa'),
    ('Canakkale'),
    ('Cankiri'),
    ('Corum'),
    ('Denizli'),
    ('Diyarbakir'),
    ('Duzce'),
    ('Edirne'),
    ('Elazig'),
    ('Erzincan'),
    ('Erzurum'),
    ('Eskisehir'),
    ('Gaziantep'),
    ('Giresun'),
    ('Gumushane'),
    ('Hakkari'),
    ('Hatay'),
    ('Igdir'),
    ('Isparta'),
    ('Istanbul'),
    ('Izmir'),
    ('Kahramanmaras'),
    ('Karabuk'),
    ('Karaman'),
    ('Kars'),
    ('Kastamonu'),
    ('Kayseri'),
    ('Kilis'),
    ('Kirikkale'),
    ('Kirklareli'),
    ('Kirsehir'),
    ('Kocaeli'),
    ('Konya'),
    ('Kutahya'),
    ('Malatya'),
    ('Manisa'),
    ('Mardin'),
    ('Mersin'),
    ('Mugla'),
    ('Mus'),
    ('Nevsehir'),
    ('Nigde'),
    ('Ordu'),
    ('Osmaniye'),
    ('Rize'),
    ('Sakarya'),
    ('Samsun'),
    ('Sanliurfa'),
    ('Siirt'),
    ('Sinop'),
    ('Sivas'),
    ('Sirnak'),
    ('Tekirdag'),
    ('Tokat'),
    ('Trabzon'),
    ('Tunceli'),
    ('Usak'),
    ('Van'),
    ('Yalova'),
    ('Yozgat'),
    ('Zonguldak')
ON CONFLICT (name) DO NOTHING;

WITH district_seed(city_name, district_name) AS (
    VALUES
        -- Istanbul
        ('Istanbul', 'Adalar'),
        ('Istanbul', 'Arnavutkoy'),
        ('Istanbul', 'Atasehir'),
        ('Istanbul', 'Avcilar'),
        ('Istanbul', 'Bagcilar'),
        ('Istanbul', 'Bahcelievler'),
        ('Istanbul', 'Bakirkoy'),
        ('Istanbul', 'Basaksehir'),
        ('Istanbul', 'Bayrampasa'),
        ('Istanbul', 'Besiktas'),
        ('Istanbul', 'Beykoz'),
        ('Istanbul', 'Beylikduzu'),
        ('Istanbul', 'Beyoglu'),
        ('Istanbul', 'Buyukcekmece'),
        ('Istanbul', 'Catalca'),
        ('Istanbul', 'Cekmekoy'),
        ('Istanbul', 'Esenler'),
        ('Istanbul', 'Esenyurt'),
        ('Istanbul', 'Eyupsultan'),
        ('Istanbul', 'Fatih'),
        ('Istanbul', 'Gaziosmanpasa'),
        ('Istanbul', 'Gungoren'),
        ('Istanbul', 'Kadikoy'),
        ('Istanbul', 'Kagithane'),
        ('Istanbul', 'Kartal'),
        ('Istanbul', 'Kucukcekmece'),
        ('Istanbul', 'Maltepe'),
        ('Istanbul', 'Pendik'),
        ('Istanbul', 'Sancaktepe'),
        ('Istanbul', 'Sariyer'),
        ('Istanbul', 'Silivri'),
        ('Istanbul', 'Sisli'),
        ('Istanbul', 'Sultanbeyli'),
        ('Istanbul', 'Sultangazi'),
        ('Istanbul', 'Tuzla'),
        ('Istanbul', 'Umraniye'),
        ('Istanbul', 'Uskudar'),
        ('Istanbul', 'Zeytinburnu'),

        -- Ankara
        ('Ankara', 'Akyurt'),
        ('Ankara', 'Altindag'),
        ('Ankara', 'Ayas'),
        ('Ankara', 'Bala'),
        ('Ankara', 'Beypazari'),
        ('Ankara', 'Cankaya'),
        ('Ankara', 'Cubuk'),
        ('Ankara', 'Elmadag'),
        ('Ankara', 'Etimesgut'),
        ('Ankara', 'Golbasi'),
        ('Ankara', 'Kecioren'),
        ('Ankara', 'Mamak'),
        ('Ankara', 'Polatli'),
        ('Ankara', 'Sincan'),
        ('Ankara', 'Yenimahalle'),

        -- Izmir
        ('Izmir', 'Aliaga'),
        ('Izmir', 'Balcova'),
        ('Izmir', 'Bayindir'),
        ('Izmir', 'Bayrakli'),
        ('Izmir', 'Bergama'),
        ('Izmir', 'Beydag'),
        ('Izmir', 'Bornova'),
        ('Izmir', 'Buca'),
        ('Izmir', 'Cesme'),
        ('Izmir', 'Cigli'),
        ('Izmir', 'Dikili'),
        ('Izmir', 'Foca'),
        ('Izmir', 'Gaziemir'),
        ('Izmir', 'Guzelbahce'),
        ('Izmir', 'Karabaglar'),
        ('Izmir', 'Karaburun'),
        ('Izmir', 'Karsiyaka'),
        ('Izmir', 'Kemalpasa'),
        ('Izmir', 'Kinik'),
        ('Izmir', 'Kiraz'),
        ('Izmir', 'Konak'),
        ('Izmir', 'Menderes'),
        ('Izmir', 'Menemen'),
        ('Izmir', 'Narlidere'),
        ('Izmir', 'Odemis'),
        ('Izmir', 'Seferihisar'),
        ('Izmir', 'Selcuk'),
        ('Izmir', 'Tire'),
        ('Izmir', 'Torbali'),
        ('Izmir', 'Urla'),

        -- Bursa
        ('Bursa', 'Buyukorhan'),
        ('Bursa', 'Gemlik'),
        ('Bursa', 'Gursu'),
        ('Bursa', 'Harmancik'),
        ('Bursa', 'Inegol'),
        ('Bursa', 'Iznik'),
        ('Bursa', 'Karacabey'),
        ('Bursa', 'Keles'),
        ('Bursa', 'Kestel'),
        ('Bursa', 'Mudanya'),
        ('Bursa', 'Mustafakemalpasa'),
        ('Bursa', 'Nilufer'),
        ('Bursa', 'Orhaneli'),
        ('Bursa', 'Orhangazi'),
        ('Bursa', 'Osmangazi'),
        ('Bursa', 'Yenisehir'),
        ('Bursa', 'Yildirim'),

        -- Antalya
        ('Antalya', 'Akseki'),
        ('Antalya', 'Aksu'),
        ('Antalya', 'Alanya'),
        ('Antalya', 'Demre'),
        ('Antalya', 'Dosemealti'),
        ('Antalya', 'Elmali'),
        ('Antalya', 'Finike'),
        ('Antalya', 'Gazipasa'),
        ('Antalya', 'Gundogmus'),
        ('Antalya', 'Ibradi'),
        ('Antalya', 'Kas'),
        ('Antalya', 'Kemer'),
        ('Antalya', 'Kepez'),
        ('Antalya', 'Konyaalti'),
        ('Antalya', 'Korkuteli'),
        ('Antalya', 'Kumluca'),
        ('Antalya', 'Manavgat'),
        ('Antalya', 'Muratpasa'),
        ('Antalya', 'Serik'),

        -- Adana
        ('Adana', 'Aladag'),
        ('Adana', 'Ceyhan'),
        ('Adana', 'Cukurova'),
        ('Adana', 'Feke'),
        ('Adana', 'Imamoglu'),
        ('Adana', 'Karaisali'),
        ('Adana', 'Karatas'),
        ('Adana', 'Kozan'),
        ('Adana', 'Pozanti'),
        ('Adana', 'Saimbeyli'),
        ('Adana', 'Saricam'),
        ('Adana', 'Seyhan'),
        ('Adana', 'Tufanbeyli'),
        ('Adana', 'Yumurtalik'),
        ('Adana', 'Yuregir'),

        -- Mersin
        ('Mersin', 'Akdeniz'),
        ('Mersin', 'Anamur'),
        ('Mersin', 'Aydincik'),
        ('Mersin', 'Bozyazi'),
        ('Mersin', 'Camliyayla'),
        ('Mersin', 'Erdemli'),
        ('Mersin', 'Gulnar'),
        ('Mersin', 'Mezitli'),
        ('Mersin', 'Mut'),
        ('Mersin', 'Silifke'),
        ('Mersin', 'Tarsus'),
        ('Mersin', 'Toroslar'),
        ('Mersin', 'Yenisehir'),

        -- Kocaeli
        ('Kocaeli', 'Basiskele'),
        ('Kocaeli', 'Cayirova'),
        ('Kocaeli', 'Darica'),
        ('Kocaeli', 'Derince'),
        ('Kocaeli', 'Dilovasi'),
        ('Kocaeli', 'Gebze'),
        ('Kocaeli', 'Golcuk'),
        ('Kocaeli', 'Izmit'),
        ('Kocaeli', 'Kandira'),
        ('Kocaeli', 'Karamursel'),
        ('Kocaeli', 'Kartepe'),
        ('Kocaeli', 'Korfez'),

        -- Konya
        ('Konya', 'Ahirli'),
        ('Konya', 'Akoren'),
        ('Konya', 'Aksehir'),
        ('Konya', 'Altinekin'),
        ('Konya', 'Beysehir'),
        ('Konya', 'Bozkir'),
        ('Konya', 'Cihanbeyli'),
        ('Konya', 'Cumra'),
        ('Konya', 'Eregli'),
        ('Konya', 'Ilgin'),
        ('Konya', 'Karatay'),
        ('Konya', 'Kulu'),
        ('Konya', 'Meram'),
        ('Konya', 'Selcuklu'),
        ('Konya', 'Seydisehir'),

        -- Gaziantep
        ('Gaziantep', 'Araban'),
        ('Gaziantep', 'Islahiye'),
        ('Gaziantep', 'Karkamis'),
        ('Gaziantep', 'Nizip'),
        ('Gaziantep', 'Nurdagi'),
        ('Gaziantep', 'Oguzeli'),
        ('Gaziantep', 'Sahinbey'),
        ('Gaziantep', 'Sehitkamil'),
        ('Gaziantep', 'Yavuzeli')
)
INSERT INTO districts (city_id, name)
SELECT c.id, s.district_name
FROM district_seed s
JOIN cities c ON c.name = s.city_name
ON CONFLICT (city_id, name) DO NOTHING;

-- Ensure at least one district exists for every city.
INSERT INTO districts (city_id, name)
SELECT c.id, 'Merkez'
FROM cities c
WHERE NOT EXISTS (
    SELECT 1 FROM districts d WHERE d.city_id = c.id
)
ON CONFLICT (city_id, name) DO NOTHING;

-- Seed one default neighborhood per district.
INSERT INTO neighborhoods (district_id, name)
SELECT d.id, 'Merkez Mahallesi'
FROM districts d
ON CONFLICT (district_id, name) DO NOTHING;

-- Seed one default region per neighborhood.
INSERT INTO regions (neighborhood_id, name)
SELECT n.id, 'Merkez Bolgesi'
FROM neighborhoods n
ON CONFLICT (neighborhood_id, name) DO NOTHING;
